"""add indexes on receipts date and category

Revision ID: 570cb81d58ff
Revises: 2b74dfb09733
Create Date: 2026-04-13 16:09:35.888763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570cb81d58ff'
down_revision: Union[str, Sequence[str], None] = '2b74dfb09733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_date'), ['date'], unique=False)
        batch_op.create_index('ix_receipts_date_category', ['date', 'category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_receipts_date_category')
        batch_op.drop_index(batch_op.f('ix_receipts_date'))
        batch_op.drop_index(batch_op.f('ix_receipts_category'))

    # ### end Alembic commands ###
